name: Test Orchestrator

on:
  workflow_dispatch: {}

jobs:
  unit-tests:
    uses: pacethomson/testing-systems-pace-thomson/.github/workflows/run_tests.yml@main

  system-tests:
    uses: pacethomson/testing-units-pace-thomson/.github/workflows/run_tests.yml@main

  behave-tests:
    uses: pacethomson/testing-with-behave-pace-thomson/.github/workflows/run_tests_behave.yml@main


# name: Test Orchestrator

# # Allows a “Run workflow” button in the Actions tab
# on:
#   workflow_dispatch: {}

# jobs:
#   run-tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           repository: JeffCompasClassrooms/testing-systems-pace-thomson

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11' # Specify your desired Python version, e.g., '3.9

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest pytest-spec requests

#       # ---- your tests go here ----
#       - name: Run test for repo 
#         run: pytest --spec
      
