name: Test Orchestrator

on:
  workflow_dispatch: {}

jobs:
  testing-units:
    runs-on: ubuntu-latest # or windows-latest, macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a recent version of the checkout action
        with:
          repository: JeffCompasClassrooms/testing-units-f25-pace-thomson

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your desired Python version, e.g., '3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==7.4.4 pytest-spec requests

      - name: Debug — list files
        run: ls -R
        
      - name: Run tests
        run: pytest --spec 

  system-tests:
    runs-on: ubuntu-latest # or windows-latest, macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a recent version of the checkout action
        with:
          repository: JeffCompasClassrooms/testing-systems-pace-thomson

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your desired Python version, e.g., '3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==7.4.4 pytest-describe pytest-spec requests

      - name: Debug — list files
        run: ls -R
        
      - name: Run tests
        run: pytest --spec test_mydb.py test_squirrel_server.py

  behave-tests:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
           python -m pip install behave==1.2.6 behave-webdriver==0.3.1 selenium==3.141.0 urllib3==1.26.18 six==1.16.0

      - name: Setup Chrome + ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      # ----- Run Behave tests -----
      - name: Run behave tests
        run: |
          echo "Running behave BDD tests"
          python -m behave computing/features 
          python -m behave isitchristmas/features 
          python -m behave peppers-ghost/features 
          python -m behave rockymountain/features 

